<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Test Newtours Site" duration-ms="25619" started-at="2017-08-05T06:59:32Z" finished-at="2017-08-05T06:59:58Z">
    <groups>
    </groups>
    <test name="Complete NewTours Site Test" duration-ms="25619" started-at="2017-08-05T06:59:32Z" finished-at="2017-08-05T06:59:58Z">
      <class name="com.bitm.selenium4thbatch.Test.LoginTest">
        <test-method status="FAIL" signature="checkHomePageTitle()[pri:0, instance:com.bitm.selenium4thbatch.Test.LoginTest@29ee9faa]" name="checkHomePageTitle" duration-ms="22368" started-at="2017-08-05T12:59:32Z" finished-at="2017-08-05T12:59:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome: Mercury Toursblabla] but found [Welcome: Mercury Tours]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome: Mercury Toursblabla] but found [Welcome: Mercury Tours]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.bitm.selenium4thbatch.Test.LoginTest.checkHomePageTitle(LoginTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomePageTitle -->
        <test-method status="PASS" signature="loginTest(java.util.List)[pri:0, instance:com.bitm.selenium4thbatch.Test.LoginTest@29ee9faa]" name="loginTest" duration-ms="1591" started-at="2017-08-05T12:59:56Z" data-provider="logindataprovider" finished-at="2017-08-05T12:59:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[LoginDto [username=demo, password=demo]]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.bitm.selenium4thbatch.Test.LoginTest -->
    </test> <!-- Complete NewTours Site Test -->
  </suite> <!-- Test Newtours Site -->
</testng-results>
